version: "3.8"
services:
  client:
    build:
      context: ./project/client/
      dockerfile: Dockerfile
    container_name: "nextjs-client"
    tty: true
    volumes:
      - ./project/client:/usr/src/client
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "npm install && npm run dev"

  db:
    build:
      context: ./project/database
      dockerfile: Dockerfile
    container_name: "mysql"
    restart: always
    volumes:
      - ./project/database/initdb.d:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
      - ./project/database/my.cnf:/etc/mysql/conf.d/my.cnf
    platform: linux/amd64
    ports:
      - "3306:3306"

  server:
    build:
      context: ./project/server
      dockerfile: Dockerfile
    container_name: "fastapi-server"
    tty: true
    volumes:
      - ./project/server:/usr/src/server
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  mysql_data:
